# Generated by Django 2.2.28 on 2023-07-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='hospital',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
